"use client";

import { ReactNode } from "react";
import {
    Activity, HeartPulse, Droplets, Moon, Flame, AlertTriangle, CheckCircle2, CalendarDays,
    Stethoscope, Download, ShieldCheck, FileText, Share2,
} from "lucide-react";
import { Card, Button, Chip } from "@/components/ui/primitives";

function Section({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) {
    return (
        <section className="border-t border-border px-6 py-5">
            <h2 className="mb-3 flex items-center gap-2 text-[13px] font-bold uppercase tracking-wide text-accent-ink">
                {icon} {title}
            </h2>
            {children}
        </section>
    );
}

function Metric({ icon, label, value, sub, tone = "ink" }: { icon: ReactNode; label: string; value: string; sub: string; tone?: "ink" | "progress" | "attention" }) {
    const valueColor = tone === "progress" ? "text-progress-ink" : tone === "attention" ? "text-attention-ink" : "text-ink";
    return (
        <div className="rounded-xl border border-border p-3">
            <div className="mb-1 flex items-center gap-1.5 text-[12px] font-medium uppercase tracking-wide text-ink-subtle">
                <span className="text-ink-muted">{icon}</span> {label}
            </div>
            <div className={`text-[18px] font-bold tabular-nums ${valueColor}`}>{value}</div>
            <div className="text-[12px] text-ink-muted">{sub}</div>
        </div>
    );
}

export function WallyReport() {
    return (
        <div className="mx-auto max-w-3xl px-5 py-8">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <span className="rounded-md bg-accent-soft px-3 py-1.5 text-[12px] font-semibold uppercase tracking-wide text-accent-ink">
                    Recovery Progress Report
                </span>
                <div className="flex gap-2">
                    <Button size="sm" variant="secondary"><Share2 size={15} strokeWidth={1.75} /> Share with care team</Button>
                    <Button size="sm"><Download size={15} strokeWidth={1.75} /> Export PDF</Button>
                </div>
            </div>

            <article className="overflow-hidden rounded-2xl border border-border bg-surface">
                {/* header */}
                <header className="px-6 py-5">
                    <div className="flex items-start justify-between gap-3">
                        <div>
                            <h1 className="text-[24px] font-bold text-ink">Recovery Progress Report</h1>
                            <p className="text-[14px] text-accent-ink">Left Hemicolectomy (Primary Anastomosis) · Post-operative Day 14</p>
                        </div>
                        <Chip tone="attention" size="md"><AlertTriangle size={14} /> Needs review</Chip>
                    </div>
                    <div className="mt-3 grid gap-x-6 gap-y-1.5 text-[13px] text-ink-muted sm:grid-cols-2">
                        <span>Patient: <span className="text-ink">Mrs Margaret Chen</span> · 62 F · NRIC S98765432B</span>
                        <span>Reporting period: <span className="text-ink">7 – 20 Jul 2026</span></span>
                        <span>Generated by: <span className="text-ink">Wally</span> (automated)</span>
                        <span>Reviewed by: <span className="text-ink">Ms Lee (PT) · Ms Wong (Dietitian)</span></span>
                    </div>
                    {/* plain-language line for the patient */}
                    <div className="mt-4 rounded-xl bg-attention-soft/40 p-3 text-[14px] text-ink">
                        <span className="font-semibold text-attention-ink">In short:</span> your walking, eating and sleep are moving
                        along — but your pain hasn&apos;t settled the way we&apos;d expect by now. We&apos;ve flagged this for your
                        care team to look at, and they may adjust your pain relief. This isn&apos;t an emergency.
                    </div>
                </header>

                {/* clinical summary */}
                <Section title="Clinical Summary" icon={<Stethoscope size={14} />}>
                    <p className="max-w-none text-[14px] leading-relaxed text-ink">
                        Mrs Margaret Chen is a 62-year-old woman, post-operative day 14 following an elective left hemicolectomy
                        with primary anastomosis for a descending colon carcinoma, convalescing at home. Engagement with the digital
                        recovery programme is strong (86% task adherence; 12 of the preceding 14 days logged). Recovery is tracking
                        behind the personalised 28-day trajectory on the pain domain, and a pain-stagnation flag has been raised for
                        clinician review. Self-reported pain has plateaued at 6/10 since day 6, improving only marginally from a
                        baseline of 8/10 and short of the expected post-operative analgesic decline. Functional mobilisation is
                        progressing per the physiotherapy protocol, with 30 minutes of continuous walking tolerated, though persistent
                        pain may be limiting further gains and is disturbing sleep. Nutritional intake meets protein and energy targets
                        on a normal-as-tolerated diet. The principal concern is the failure of pain to settle as anticipated; hydration
                        is intermittently suboptimal.
                    </p>
                </Section>

                {/* metrics */}
                <Section title="Key Metrics" icon={<Activity size={14} />}>
                    <div className="grid gap-3 sm:grid-cols-3">
                        <Metric icon={<CheckCircle2 size={13} />} label="Adherence" value="86%" sub="12 of 14 days logged" tone="progress" />
                        <Metric icon={<AlertTriangle size={13} />} label="Pain" value="8 → 6 / 10" sub="plateaued since day 6" tone="attention" />
                        <Metric icon={<Activity size={13} />} label="Mobility" value="30 min" sub="continuous walking tolerated" tone="progress" />
                        <Metric icon={<Flame size={13} />} label="Protein" value="≈ 90 g/day" sub="at target (80–100 g)" tone="progress" />
                        <Metric icon={<Droplets size={13} />} label="Hydration" value="Variable" sub="dark urine on 2 days" tone="attention" />
                        <Metric icon={<Moon size={13} />} label="Sleep" value="Disrupted" sub="ongoing pain, nocturia" tone="attention" />
                    </div>
                </Section>

                {/* insights */}
                <Section title="Key Insights" icon={<HeartPulse size={14} />}>
                    <ol className="list-decimal space-y-2 pl-5 text-[14px] leading-snug text-ink">
                        <li><span className="font-medium">Pain is not settling as expected</span> — scores have plateaued around 6/10 since day 6, short of the projected post-operative decline. A pain-stagnation flag has been raised for clinician review of analgesia.</li>
                        <li>Functional mobilisation is progressing per protocol, though persistent pain may be capping further gains and is disturbing sleep.</li>
                        <li>Nutritional intake meets protein and energy requirements on a normal-as-tolerated diet.</li>
                        <li>Hydration is intermittently suboptimal — reinforcement is advised to mitigate dehydration-related readmission, a recognised driver of post-colectomy readmissions.</li>
                        <li>No red-flag symptomatology (fever, escalating abdominal pain, persistent vomiting, intolerance of oral intake) reported; the pain is persistent but non-escalating.</li>
                    </ol>
                </Section>

                {/* recommended actions */}
                <Section title="Recommended Actions" icon={<CalendarDays size={14} />}>
                    <ul className="space-y-2 text-[14px] leading-snug text-ink">
                        {[
                            "Clinician review of analgesia — pain has not settled as expected; consider revisiting the current regimen.",
                            "Continue physiotherapy and dietetic regimens; monitor whether pain is limiting mobilisation.",
                            "Optimise hydration to ≥ 1.5–2 L/day; enable scheduled fluid prompts.",
                            "Bring forward the post-discharge review in light of the pain-stagnation flag (21 Jul 2026, 10:00).",
                            "Safety-net advice reiterated; re-present should red-flag features (fever, escalating pain, vomiting) develop.",
                        ].map((a) => (
                            <li key={a} className="flex gap-2.5">
                                <CheckCircle2 size={16} strokeWidth={2} className="mt-0.5 shrink-0 text-accent-ink" /> {a}
                            </li>
                        ))}
                    </ul>
                </Section>

                {/* safety status */}
                <Section title="Safety Status" icon={<ShieldCheck size={14} />}>
                    <p className="inline-flex items-center gap-2 rounded-lg bg-attention-soft/40 px-3 py-2 text-[14px] text-attention-ink">
                        <AlertTriangle size={16} /> 1 active flag — pain stagnation. Clinician review requested; not an emergency escalation.
                    </p>
                </Section>

                <footer className="flex items-center gap-2 border-t border-border bg-surface-sunken/40 px-6 py-3 text-[12px] text-ink-subtle">
                    <FileText size={13} /> Auto-generated by Wally from patient-reported data · for clinician review · not a substitute for direct assessment.
                </footer>
            </article>
        </div>
    );
}
