"use client";

import { ReactNode } from "react";
import {
    Activity, HeartPulse, Droplets, Moon, Flame, TrendingDown, CheckCircle2, CalendarDays,
    Stethoscope, Download, ShieldCheck, FileText, Share2,
} from "lucide-react";
import { Card, Button, Chip } from "@/components/ui/primitives";

function Section({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) {
    return (
        <section className="border-t border-border px-6 py-5">
            <h2 className="mb-3 flex items-center gap-2 text-[13px] font-bold uppercase tracking-wide text-accent-ink">
                {icon} {title}
            </h2>
            {children}
        </section>
    );
}

function Metric({ icon, label, value, sub, tone = "ink" }: { icon: ReactNode; label: string; value: string; sub: string; tone?: "ink" | "progress" | "attention" }) {
    const valueColor = tone === "progress" ? "text-progress-ink" : tone === "attention" ? "text-attention-ink" : "text-ink";
    return (
        <div className="rounded-xl border border-border p-3">
            <div className="mb-1 flex items-center gap-1.5 text-[12px] font-medium uppercase tracking-wide text-ink-subtle">
                <span className="text-ink-muted">{icon}</span> {label}
            </div>
            <div className={`text-[18px] font-bold tabular-nums ${valueColor}`}>{value}</div>
            <div className="text-[12px] text-ink-muted">{sub}</div>
        </div>
    );
}

export function WallyReport() {
    return (
        <div className="mx-auto max-w-3xl px-5 py-8">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <span className="rounded-md bg-accent-soft px-3 py-1.5 text-[12px] font-semibold uppercase tracking-wide text-accent-ink">
                    Recovery Progress Report
                </span>
                <div className="flex gap-2">
                    <Button size="sm" variant="secondary"><Share2 size={15} strokeWidth={1.75} /> Share with care team</Button>
                    <Button size="sm"><Download size={15} strokeWidth={1.75} /> Export PDF</Button>
                </div>
            </div>

            <article className="overflow-hidden rounded-2xl border border-border bg-surface">
                {/* header */}
                <header className="px-6 py-5">
                    <div className="flex items-start justify-between gap-3">
                        <div>
                            <h1 className="text-[24px] font-bold text-ink">Recovery Progress Report</h1>
                            <p className="text-[14px] text-accent-ink">Laparoscopic Sigmoid Colectomy (Anastomosis) · Post-operative Day 14</p>
                        </div>
                        <Chip tone="progress" size="md"><CheckCircle2 size={14} /> On track</Chip>
                    </div>
                    <div className="mt-3 grid gap-x-6 gap-y-1.5 text-[13px] text-ink-muted sm:grid-cols-2">
                        <span>Patient: <span className="text-ink">Mr Tan</span> · 40 M · NRIC S1234567A</span>
                        <span>Reporting period: <span className="text-ink">28 May – 10 Jun 2025</span></span>
                        <span>Generated by: <span className="text-ink">Wally</span> (automated)</span>
                        <span>Reviewed by: <span className="text-ink">Ms Lee (PT) · Ms Wong (Dietitian)</span></span>
                    </div>
                    {/* plain-language line for the patient */}
                    <div className="mt-4 rounded-xl bg-progress-soft/40 p-3 text-[14px] text-ink">
                        <span className="font-semibold text-progress-ink">In short:</span> your recovery is on track. Keep up the daily
                        walks and protein — the main thing to work on is drinking more water through the day.
                    </div>
                </header>

                {/* clinical summary */}
                <Section title="Clinical Summary" icon={<Stethoscope size={14} />}>
                    <p className="max-w-none text-[14px] leading-relaxed text-ink">
                        Mr Tan is a 40-year-old gentleman, post-operative day 14 following an elective laparoscopic sigmoid colectomy
                        with primary anastomosis for sigmoid colonic carcinoma, convalescing at home. Engagement with the digital
                        recovery programme is strong (86% task adherence; 12 of the preceding 14 days logged). Recovery is tracking
                        favourably against the personalised 28-day trajectory, with no clinician escalation triggered to date.
                        Self-reported pain has declined from a baseline of 8/10 to 2/10, consistent with the expected post-operative
                        analgesic curve and without breakthrough escalation. Functional mobilisation is progressing per the
                        physiotherapy protocol, with 30 minutes of continuous walking tolerated and graduated resistance work
                        commenced without adverse symptoms. Nutritional intake meets protein and energy targets on a
                        normal-as-tolerated diet. The principal modifiable concern is intermittently suboptimal hydration.
                    </p>
                </Section>

                {/* metrics */}
                <Section title="Key Metrics" icon={<Activity size={14} />}>
                    <div className="grid gap-3 sm:grid-cols-3">
                        <Metric icon={<CheckCircle2 size={13} />} label="Adherence" value="86%" sub="12 of 14 days logged" tone="progress" />
                        <Metric icon={<TrendingDown size={13} />} label="Pain" value="8 → 2 / 10" sub="declining as expected" tone="progress" />
                        <Metric icon={<Activity size={13} />} label="Mobility" value="30 min" sub="continuous walking tolerated" tone="progress" />
                        <Metric icon={<Flame size={13} />} label="Protein" value="≈ 90 g/day" sub="at target (80–100 g)" tone="progress" />
                        <Metric icon={<Droplets size={13} />} label="Hydration" value="Variable" sub="dark urine on 2 days" tone="attention" />
                        <Metric icon={<Moon size={13} />} label="Sleep" value="Improving" sub="early disruption: pain, nocturia" tone="ink" />
                    </div>
                </Section>

                {/* insights */}
                <Section title="Key Insights" icon={<HeartPulse size={14} />}>
                    <ol className="list-decimal space-y-2 pl-5 text-[14px] leading-snug text-ink">
                        <li>Analgesic trajectory is appropriate; pain scores are declining in line with the expected post-operative curve, without breakthrough escalation.</li>
                        <li>Functional mobilisation is progressing per protocol; activity is self-rated low-difficulty, supporting safe graduated loading.</li>
                        <li>Nutritional intake meets protein and energy requirements on a normal-as-tolerated diet.</li>
                        <li><span className="font-medium">Hydration is the principal modifiable risk</span> — intermittent suboptimal fluid intake; reinforcement is advised to mitigate dehydration-related readmission, a recognised driver of post-colectomy readmissions.</li>
                        <li>No red-flag symptomatology (fever, escalating abdominal pain, persistent vomiting, intolerance of oral intake) reported during the period.</li>
                    </ol>
                </Section>

                {/* recommended actions */}
                <Section title="Recommended Actions" icon={<CalendarDays size={14} />}>
                    <ul className="space-y-2 text-[14px] leading-snug text-ink">
                        {[
                            "Continue the current physiotherapy and dietetic regimens without modification.",
                            "Optimise hydration to ≥ 1.5–2 L/day; enable scheduled fluid prompts.",
                            "Maintain protein intake at 80–100 g/day.",
                            "Proceed to routine 2-week post-discharge review (11 Jun 2025, 10:00).",
                            "Safety-net advice reiterated; re-present should red-flag features develop.",
                        ].map((a) => (
                            <li key={a} className="flex gap-2.5">
                                <CheckCircle2 size={16} strokeWidth={2} className="mt-0.5 shrink-0 text-accent-ink" /> {a}
                            </li>
                        ))}
                    </ul>
                </Section>

                {/* safety status */}
                <Section title="Safety Status" icon={<ShieldCheck size={14} />}>
                    <p className="inline-flex items-center gap-2 rounded-lg bg-progress-soft/40 px-3 py-2 text-[14px] text-progress-ink">
                        <ShieldCheck size={16} /> No active flags. No clinician escalation indicated at this time.
                    </p>
                </Section>

                <footer className="flex items-center gap-2 border-t border-border bg-surface-sunken/40 px-6 py-3 text-[12px] text-ink-subtle">
                    <FileText size={13} /> Auto-generated by Wally from patient-reported data · for clinician review · not a substitute for direct assessment.
                </footer>
            </article>
        </div>
    );
}
