import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers"; // Import the new provider
import Sidebar from '@/components/layout/Sidebar'; 

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Sidebar /> {/* The fixed sidebar */}
        <main className="ml-16 transition-all duration-300 ease-in-out"> 
          {/* ml-16 creates space for the collapsed sidebar */}
          {children}
        </main>
      </body>
    </html>
  );
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
