import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Pinecone } from "@pinecone-database/pinecone";
import { OpenAI } from "openai";

// Initialize external clients
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: NextRequest) {
    try {
        const { userId, currentDay } = await req.json();

        if (!userId || !currentDay) {
            return NextResponse.json({ error: "Missing userId or currentDay" }, { status: 400 });
        }

        // 1. Fetch Previous Day's Feedback from Database
        // We look for the State record from the previous day (currentDay - 1)
        // Optimization: In a real app, dateCreated would be a Date object, here assuming chronological order or simple date logic
        // For MVP, we'll fetch the *latest* state before today.
        
        const lastState = await prisma.state.findFirst({
            where: { userId: userId },
            orderBy: { dateCreated: 'desc' },
            include: {
                modules: { include: { progress: true } }
            }
        });

        let patientContext = `Current Post-Op Day: ${currentDay}`;
        if (lastState) {
            // Extract Feedback from the generic modules relation (keyed by type)
            const nutritionModule = lastState.modules.find((m) => m.type === "nutrition");
            const exerciseModule = lastState.modules.find((m) => m.type === "exercise");
            const nutritionFeedback = nutritionModule?.progress?.trackables ?? "No nutrition data";
            const exerciseFeedback = exerciseModule?.progress?.trackables ?? "No exercise data";

            patientContext += `\nYesterday's Feedback:\n- Nutrition: ${JSON.stringify(nutritionFeedback)}\n- Exercise: ${JSON.stringify(exerciseFeedback)}`;
        } else {
            patientContext += "\nNo previous feedback found (First day or new user).";
        }

        console.log("Patient Context constructed:", patientContext);

        // 2. RAG Retrieval (Integrated Inference)
        // Instead of generating embeddings locally with OpenAI, we send the text query to Pinecone's inference API
        // to get the query vector, then query the index.
        
        const pinecone = new Pinecone({ apiKey: process.env.PINECONE_API_KEY! });
        const pineconeIndex = pinecone.Index(process.env.PINECONE_INDEX!);

        // Generate Query Vector using Nvidia model
        const retrievalQuery = `Recovery guidelines for Day ${currentDay} colorectal surgery complications pain nutrition`;
        
        const queryEmbedding = await pinecone.inference.embed(
            "nvidia-llama-text-embed-v2",
            [retrievalQuery],
            { inputType: "query" }
        );

        const queryResponse = await pineconeIndex.query({
            vector: (queryEmbedding as any)[0].values,
            topK: 3,
            includeMetadata: true
        });

        const contextText = queryResponse.matches
            .map(match => (match.metadata as any)?.text || "")
            .filter(Boolean)
            .join("\n\n");

        // 3. LLM Generation
        const systemPrompt = `
You are a specialized Recovery Assistant for Colorectal Surgery.
Task: Generate a customized plan for Day ${currentDay}.
Context:
${contextText}

Patient Status:
${patientContext}

Instructions:
- If user reported high pain (>5/10) or low intake (<50%), suggest easier alternatives and reference safety guidelines.
- Output JSON format with "nutrition" and "exercise" fields containing specific tasks.
`;

        const completion = await openai.chat.completions.create({
            model: "gpt-4-turbo-preview",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: "Generate the JSON plan." }
            ],
            response_format: { type: "json_object" }
        });

        const content = completion.choices[0].message.content;
        if (!content) {
             throw new Error("No content generated by LLM");
        }
        
        const planJson = JSON.parse(content);

        // 4. Save to DB (Create New State for Current Day)
        const newState = await prisma.state.create({
            data: {
                userId: userId,
                dateCreated: new Date(),
                isActive: true,
                modules: {
                    create: [
                        {
                            type: "nutrition",
                            plan: planJson.nutrition ?? {},
                            summary: "AI Generated Nutrition Plan"
                        },
                        {
                            type: "exercise",
                            plan: planJson.exercise ?? {},
                            summary: "AI Generated Exercise Plan"
                        }
                    ]
                }
            }
        });

        return NextResponse.json({ success: true, plan: planJson, stateId: newState.id });

    } catch (error) {
        console.error("Plan Generation Error:", error);
        return NextResponse.json({ error: "Failed to generate plan" }, { status: 500 });
    }
}
