# This file overrides the default proxy settings set by Elastic Beanstalk.
# We remove the EB default and set it to our custom upstream called 'uvicorn'.

include conf.d/elasticbeanstalk/mime.types;
default_type application/octet-stream;

# Use our custom upstream defined in myapp.conf (port 5000)
proxy_pass http://uvicorn; 

proxy_set_header   Connection "";
proxy_http_version 1.1;
proxy_set_header        Host            $host;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;